### ISSUE TITLE
Persistent registration modal after registering

### ISSUE THREAD

**Issue by ltephanysopez** [Hack-DSC/webapp#3]
Registration modal keeps popping up after a user has already registered

**Comment by Apexal** [comment]
What domain are you on `hack-dsc.web.app`, `hack-dsc.firebaseapp.com`, or `hackdsc.com`? @ltephanysopez

**Comment by ltephanysopez** [comment]
`hack-dsc.firebaseapp.com`

**Comment by Apexal** [comment]
does it happen on `hackdsc.com`?

**Comment by ltephanysopez** [comment]
no- I think it may have persisted bc of a new input on the modal (gender?) that wasn't there when I first filled it out
